language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest -vvv antialiasing/ --cov antialiasing/src

after_success:
  - codecov

branches:
  only:
    - master