language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/antialiasing

script:
  - pytest --cov=antialiasing/src

after_success:
  - codecov

branches:
  only:
    - master